---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://oauth2-proxy.github.io/manifests
      chart: oauth2-proxy
      version: 3.2.6
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: "quay.io/oauth2-proxy/oauth2-proxy"
      tag: "v7.0.1"
    replicaCount: 2
    # tolerations:
    #   - key: "arm"
    #     operator: "Exists"
    ingress:
      enabled: true
      path: /oauth2
      hosts: [auth.eviljungle.com]
      tls:
      - hosts:
        - auth.eviljungle.com
    extraArgs:
      provider: oidc
      oidc-issuer-url: https://billimek.auth0.com/
      skip-provider-button:
      pass-authorization-header:
      email-domain: "*"
      cookie-domain: .eviljungle.com
      whitelist-domain: .eviljungle.com
  valuesFrom:
  - kind: Secret
    name: "oauth2-proxy-helm-values"
    optional: false
